### ISSUE TITLE
[Improvement] pickle support 

### ISSUE THREAD

**Issue by geoHeil** [ArdalanM/pyLightGBM#12]
The xgboost sklearn wrapper for python has pickle support. It would be great if lightgbm models could be serialized just as easy.

**Comment by ArdalanM** [comment]
I am able to `pickle.dump` and `pickle.load` the trained model.  Added  a quick example [here](https://github.com/ArdalanM/pyLightGBM/blob/master/examples/save_load_model.py) if you want to try.

Is that what you were looking for ?

**Comment by geoHeil** [comment]
Indeed. Thanks a lot. Do I understand correctly that the original lightGBM model is included in the pickled output e.g. no longer required?

**Comment by ArdalanM** [comment]
In a nutshell, yes.

LightGBM has the following parameter:
`output_model, default=LightGBM_model.txt, type=string, alias=model_output,model_out`
which contains the information about the trained model, used for prediction.

This string is stored as `self.model` so you should be able to pickle/unpickle with ease :)

**Comment by geoHeil** [comment]
I see so I will require the pickled model AND the serialized model / txt files.

**Comment by ArdalanM** [comment]
You only need the pickled model.

The txt file and all necessary information are contained in the model when you `pickle.dump` it.
