### ISSUE TITLE
file format issues

### ISSUE THREAD

**Issue by geoHeil** [ArdalanM/pyLightGBM#20]
sometimes I get 
`input format error, should be LibSVMinput format error, should be LibSVM` but have no real clue how to debug it. Do you have any suggestions?

The strange thing is that the training worked just fine:

```
[LightGBM] [Info] 3.972398 seconds elapsed, finished 59 iteration
[LightGBM] [Info] 4.042168 seconds elapsed, finished 60 iteration
[LightGBM] [Info] Finish train
```

The problem occurs when I try to predict new values.

**Comment by geoHeil** [comment]
I can reproduce it with the latest build of lightgbm and the notebook from https://github.com/ArdalanM/pyLightGBM/blob/master/notebooks/regression_example_kaggle_allstate.ipynb

**Comment by ArdalanM** [comment]
Having the same issue.
I think libSVM format handling has been updated by LightGBM. 
Opened an issue: https://github.com/Microsoft/LightGBM/issues/54

Hope they fix it quickly.
Thanks for the feedback :+1:

**Comment by geoHeil** [comment]
I can confirm that their latest changes fix the problem.
