### ISSUE TITLE
dart, max_depth

### ISSUE THREAD

**Issue by gugatr0n1c** [ArdalanM/pyLightGBM#31]
Hi @ArdalanM , can you please support also dart (boosting, drop_rate) and max_depth params?

thx

**Comment by ArdalanM** [comment]
Done, added an [example](https://github.com/ArdalanM/pyLightGBM/blob/master/examples/binary_classification.py) with `dart` booster

**Comment by gugatr0n1c** [comment]
@ArdalanM great!, thx for quick reply

**Comment by gugatr0n1c** [comment]
@ArdalanM dart is working, but max_depth seems to be not implemented... thx for review
