### ISSUE TITLE
new param max_depth added in LightGBM

### ISSUE THREAD

**Issue by gugatr0n1c** [ArdalanM/pyLightGBM#34]
Hi,

in LightGBM there is new setting for control overfitting for small datasets: max_depth

https://github.com/Microsoft/LightGBM/pull/35

thx for adding

**Comment by ArdalanM** [comment]
it's already [included](https://github.com/ArdalanM/pyLightGBM/blob/master/pylightgbm/models.py#L45) in the wrapper

**Comment by gugatr0n1c** [comment]
sorry, I have not downloadad lastest version, confirming, it is working.. thx
