### ISSUE TITLE
'LIGHTGBM_EXEC' environment variable, cannot be found

### ISSUE THREAD

**Issue by cbjorgol** [ArdalanM/pyLightGBM#41]
The examples show:

    path_to_exec = "~/Documents/apps/LightGBM/lightgbm"

This path does not exist in the package

    ls /Users/me/LightGBM/
    CMakeLists.txt	README.md	docs		include		python-package	tests
    LICENSE		build		examples	pmml		src		windows

...and when I try to build a model I get an error

    from pylightgbm.models import GBMClassifier

    df = pd.read_csv('my_data.csv')
    
    params = {'exec_path': path_to_exec,
          'num_iterations': 1000, 'learning_rate': 0.01,
          'min_data_in_leaf': 1, 'num_leaves': 5,
          'metric': 'binary_error', 'verbose': False,
          'early_stopping_round': 20}

    GBMClassifier(params).fit(df['X_var'], df['y_var'])

    pyLightGBM is looking for 'LIGHTGBM_EXEC' environment variable, cannot be found.
    exec_path will be deprecated in favor of environment variable

    /Users/me/anaconda/lib/python2.7/site-packages/pylightgbm/models.pyc in fit(self, X, y, test_data, init_scores)
        129 
        130             process = subprocess.Popen([self.exec_path, "config={}".format(conf_filepath)],
    --> 131                                        stdout=subprocess.PIPE, bufsize=1)
        132 
        133         else:

    /Users/me/anaconda/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
        708                                 p2cread, p2cwrite,
        709                                 c2pread, c2pwrite,
    --> 710                                 errread, errwrite)
        711         except Exception:
        712             # Preserve original exception in case os.close raises.

    /Users/me/anaconda/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
       1333                         raise
       1334                 child_exception = pickle.loads(data)
    -> 1335                 raise child_exception
       1336 
       1337 

    OSError: [Errno 13] Permission denied

**Comment by McSim** [comment]
I have got the same error yestaday. 
I added "import os" with environment variable 'LIGHTGBM_EXEC'.

**Comment by cbjorgol** [comment]
So it turned out that I missed a step and didn't run `make -j4` so it couldn't find the package which shot me a weird permission denied error.  Stupid mistake on my part but it's working now.

I do get the weird message @McSim mentioned but `os.environ['LIGHTGBM_EXEC'] = exec_path` cleared that up for me too.  

Cool package!
