### ISSUE TITLE
result file not found

### ISSUE THREAD

**Issue by geoHeil** [ArdalanM/pyLightGBM#5]
A clf.predict(X) seems to cause a
`FileNotFoundError: [Errno 2] No such file or directory: 'pathToLightGBM/lightgbm_models/32028_1476974477/LightGBM_predict_result_32028_1476974523.txt'
` for me.
I just downloaded the package from github and created a GBMClassifier - not sure if install via pip ... would be required.
# edit

I am using a mac / osx 10.11.6 

but I can see the files in the finder:
# edit2

I noticed, that no `LightGBM_predict_result_32028_1476974809.txt` result.txt but rather only 3 other files were created.

![lightgbm_models](https://cloud.githubusercontent.com/assets/1694964/19564954/840b997c-96e5-11e6-8b3a-6de18eefe523.jpg)

**Comment by ArdalanM** [comment]
Does running the examples work for you ?

**Comment by geoHeil** [comment]
nope. But it does not generate the output file LightGBM_predict_result_32028_1476974809.txt

**Comment by ArdalanM** [comment]
Install via pip works for me: 
`pip install git+https://github.com/ArdalanM/pyLightGBM.git`

I am able to reproduce your error when the `exec_path` is not set correctly.

`exec_path` is the path to the lightgbm executable you installed here: https://github.com/Microsoft/LightGBM
For example, mine is located at:

```
/home/ardalan/Documents/apps/LightGBM/lightgbm
```

**Comment by geoHeil** [comment]
indeed. Thanks a lot. I found my issue.
