### ISSUE TITLE
max_bin and early_stopping_rounds

### ISSUE THREAD

**Issue by yychenca** [ArdalanM/pyLightGBM#8]
Thank you @ArdalanM for creating the wrapper which looks great!

Is it possible to:
1. add max_bin to the parameters
2. add a verbose/ silent flag to control if LightGBM's running message could be printed out, this can be of help for:
3. extract the best rounds from the running message if early stopping is used.

Thanks,

**Comment by ihopethiswillfi** [comment]
I just logged in to ask exactly the same as 2) and 3).  I just trained a model with early_stopping, but after the training I had no idea how many rounds it trained for and which round was the best one.

**Comment by EBazarov** [comment]
Thank you for your reply, you are right it will be very useful.

This features in our roadmap :)

**Comment by ArdalanM** [comment]
@yychenca, @ihopethiswillfi, just update master with your requests:
- `max_bin` parameter
- `verbose`: if `False` will silent the lightgbm's output
- `clf.best_round`:  to get best number of round based on `test_data`  :)

**Comment by yychenca** [comment]
Brilliant! Thank you so much Ardalan.
